### ISSUE TITLE
ChordChart.fretStart doesn't affect ChordWidget display

### ISSUE THREAD

**Issue by cullub** [chRyNaN/GuitarChords#1]
Setting ``ChordChart.fretStart`` does not change where the widget displays the first fret.  The number of frets displayed will consistently be ``fretEnd - fretStart``, but setting `fretStart = 5` should make the first (top) fret displayed be fret number 5.

I'm using Kotlin for Android, and Chords version 2.1.0.  Here's some relevant code:

```
val defaultChordChart = ChordChart.STANDARD_TUNING_GUITAR_CHART
chordWidget.chord = myChord
chordWidget.chart = defaultChordChart.copy(fretStart = 5, fretEnd = 6)
```

This results in frets 1 and 2 being shown.  Note that when fret labels are turned on, they are correctly positioned, and the right numbers as well (i.e., frets 5 and 6 would be labeled in this case, although they wouldn't be shown since only the first two frets are shown here).

* Library Version: [2.1.0]

**Comment by cullub** [comment]
The above pull request fixes this issue.

**Comment by chRyNaN** [comment]
This has been fixed in the PR: https://github.com/chRyNaN/chords/pull/2
